# Generated by Django 3.1 on 2020-09-01 12:55

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='age',
            field=models.CharField(choices=[('Young', 'YOUNG'), ('Old', 'OLD')], default=None, max_length=5),
        ),
        migrations.AddField(
            model_name='animal',
            name='animal',
            field=models.CharField(choices=[('Cat', 'CAT'), ('Dog', 'DOG'), ('Bird', 'BIRD'), ('Reptile', 'REPTILE')], default=None, max_length=7),
        ),
        migrations.AddField(
            model_name='animal',
            name='description',
            field=models.TextField(default=None, max_length=400),
        ),
        migrations.AddField(
            model_name='animal',
            name='difficulty',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='animal',
            name='gender',
            field=models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE')], default=None, max_length=6),
        ),
        migrations.AddField(
            model_name='animal',
            name='image',
            field=models.ImageField(default=None, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='animal',
            name='sheltered',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
